### ISSUE TITLE
Dynamic user home dir

### ISSUE THREAD

**Issue by mjarkk** [dennis1248/quick-dd#1]
Someone else needs to change the code to get this working on there PC because of this line: [quick-dd.py#L33](https://github.com/dennis1248/quick-dd/blob/master/source/quick-dd.py#L33) there you have a static home dir.  
This might be the answer https://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python

**Comment by dennis1248** [comment]
Done :-)
