### ISSUE TITLE
print(str(targetPath) + ' is selected') Runs twice

### ISSUE THREAD

**Issue by dennis1248** [dennis1248/quick-dd#2]
`print(str(targetPath) + ' is selected')` is run twice. I can't figure out why.. 

```
What is the target disk? sdc
/dev/sdc is selected
/dev/sdc is selected
From which pool do you wish to select an image?
```

**Comment by mjarkk** [comment]
I think this line needs to be removed: [quick-dd.py#L48](https://github.com/dennis1248/quick-dd/blob/master/source/quick-dd.py#L48)

**Comment by dennis1248** [comment]
Yup :+1:
